# Generated by Django 3.1.3 on 2021-02-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empCode', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Saved'), (2, 'Submitted'), (3, 'Approved')], default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department')),
            ],
        ),
    ]
